name: Clojure CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
      with:
        submodules: recursive
    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@13.5.2
      with:
        cli: latest
    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.clojure/.cpcache
        key: clojure-${{ hashFiles('deps.edn') }}
        restore-keys: clojure-
    - name: Install dependencies
      run: clojure -P && clojure -P -M:test && clojure -P -M:cljstyle-check && clojure -P -T:build
    - name: Check formatting
      run: clojure -M:cljstyle-check
    - name: Check for outdated dependencies
      run: clojure -T:build outdated
    - name: Run tests
      run: clojure -M:test
